### ISSUE TITLE
Scan Error Count Verbose Output

### ISSUE THREAD

**Issue by billybco** [Qualys/osslscanwin#1]
I might be overlooking something, but is there output for any Scan Errors reported? Would be nice to take a closer look at any files or paths that generated errors during a scan.

**Comment by romw** [comment]
There is a '/v' command line switch which should print out which directories were unable to be scanned for one reason or another.  Most of the time it is a system directory Windows is protecting.

I'll add the '/v' command line option to the help output.  I thought that was previously documented.
